const REQUSET_MAIN_LIST_START = 'REQUSET_MAIN_LIST_START';


const REQUSET_MAIN_LIST_SUCCESS = 'REQUSET_MAIN_LIST_SUCCESS';

const REQUSET_MAIN_LIST_FAILED = 'REQUSET_MAIN_LIST_FAILED';

export {
REQUSET_MAIN_LIST_START,
REQUSET_MAIN_LIST_SUCCESS,
REQUSET_MAIN_LIST_FAILED
}
