
const REQUSET_SHARE_START = 'REQUSET_SHARE_START';

const REQUSET_SHARE_SUCCESS = 'REQUSET_SHARE_SUCCESS';

const REQUEST_SHARE_FAILED = 'REQUEST_SHARE_FAILED';

export {
REQUSET_SHARE_START,
REQUSET_SHARE_SUCCESS,
REQUEST_SHARE_FAILED
}